/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TlsOptions {
  rejectUnauthorized: boolean
}
export interface LdapOpts {
  url: string
  connectTimeout?: number
  tlsOptions?: TlsOptions
}
export interface AuthOpts {
  ldapOpts: LdapOpts
  userSearchBase: string
  usernameAttribute: string
  username: string
  adminDn?: string
  adminPassword?: string
  userDn?: string
  userPassword?: string
  verifyUserExists?: boolean
  attributes?: Array<string>
  starttls?: boolean
  groupsSearchBase?: string
  groupClass?: string
  groupMemberAttribute?: string
  groupMemberUserAttribute?: string
}
export declare function authenticate(authOpts: AuthOpts): Promise<string>
